name = "lustre_components"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[javascript]
runtime = "node"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
